name: openforcefield
channels:
    - omnia
    - conda-forge
    - rdkit
dependencies:
    - python ==3.6
    - numpy
    - setuptools
    - openmm
    - parmed
    - numpydoc
    - networkx
    - lxml
    - icu 58*  # This is a lxml dependency but sometimes conda installs version 56
    - openmoltools >=0.7.3
    - matplotlib
    - pandas
    - nbsphinx
    - sphinx_bootstrap_theme
    - m2r >=0.2.1
    - rdkit
    - testpath =0.3.1
    - packmol
    - pymbar
    - mdtraj
    - dask
    - pip:
      - arch
